using static DIKtoUnityMapping;
public interface ITranslator : IMemory
{
    public string GetBuffer();
    public string Describe(int _key);
    public bool Translate(int _key, out char c);
    public char KeySymbol(int _key, int _state);
    public void SwitchRus();
    public int GetState();
    public int GetShift();
    public int GetCtrl();
    public int GetAlt();
    public int UseShift(bool data);
    public int UseCtrl(bool data);
    public int UseAlt(bool data);
    public bool SetExec(bool data);
    public bool SetKey(in string keyName, int mod, in string value);
    public bool ClearKey(in string keyName, int mod);
    public bool ProcessKeyPress(int _key, int _code);
};

public interface ITranslator2 : ITranslator
{
    public bool SetKeyEx(in string keyName, in string value);
    public bool ClearKeyEx(in string keyName);

    public static readonly KeyDefinition[] keybord = { //Да, в исходниках именно keybord
    new KeyDefinition(DIK_ESCAPE      ,"ESCAPE"),
    new KeyDefinition(DIK_1           ,"1","1!  "),
    new KeyDefinition(DIK_2           ,"2","2@  "),
    new KeyDefinition(DIK_3           ,"3","3#  "),
    new KeyDefinition(DIK_4           ,"4","4$  "),
    new KeyDefinition(DIK_5           ,"5","5%  "),
    new KeyDefinition(DIK_6           ,"6","6^  "),
    new KeyDefinition(DIK_7           ,"7","7&  "),
    new KeyDefinition(DIK_8           ,"8","8*  "),
    new KeyDefinition(DIK_9           ,"9","9(  "),
    new KeyDefinition(DIK_0           ,"0","0)  "),
    new KeyDefinition(DIK_MINUS       ,"ACCENTO","\"?  "),
    new KeyDefinition(DIK_EQUALS      ,"I_ACCENTATA","м^  "),
    new KeyDefinition(DIK_BACK        ,"BACKSPACE"),
    new KeyDefinition(DIK_TAB         ,"TAB"),
    new KeyDefinition(DIK_Q           ,"Q","qQ  "),
    new KeyDefinition(DIK_W           ,"W","wW  "),
    new KeyDefinition(DIK_E           ,"E","eE  "),
    new KeyDefinition(DIK_R           ,"R","rR  "),
    new KeyDefinition(DIK_T           ,"T","tT  "),
    new KeyDefinition(DIK_Y           ,"Y","yY  "),
    new KeyDefinition(DIK_U           ,"U","uU  "),
    new KeyDefinition(DIK_I           ,"I","iI  "),
    new KeyDefinition(DIK_O           ,"O","oO  "),
    new KeyDefinition(DIK_P           ,"P","pP"  ),
    new KeyDefinition(DIK_LBRACKET    ,"E_ACCENTATA","ий  "),
    new KeyDefinition(DIK_RBRACKET    ,"PIU","+*  "),
    new KeyDefinition(DIK_RETURN      ,"ENTER"),
    new KeyDefinition(DIK_LCONTROL    ,"LCTRL"),
    new KeyDefinition(DIK_A           ,"A","aA  "),
    new KeyDefinition(DIK_S           ,"S","sS  "),
    new KeyDefinition(DIK_D           ,"D","dD  "),
    new KeyDefinition(DIK_F           ,"F","fF  "),
    new KeyDefinition(DIK_G           ,"G","gG  "),
    new KeyDefinition(DIK_H           ,"H","hH  "),
    new KeyDefinition(DIK_J           ,"J","jJ  "),
    new KeyDefinition(DIK_K           ,"K","kK  "),
    new KeyDefinition(DIK_L           ,"L","lL  "),
    new KeyDefinition(DIK_SEMICOLON   ,"O_ACCENTATA","тз  "),
    new KeyDefinition(DIK_APOSTROPHE  ,"A_ACCENTATA","а°  "),
    new KeyDefinition(DIK_GRAVE       ,"TILDA","`~  "),
    new KeyDefinition(DIK_LSHIFT      ,"LSHIFT"),
    new KeyDefinition(DIK_BACKSLASH   ,"U_ACCENTATA","щ§  "),
    new KeyDefinition(DIK_Z           ,"Z","zZ  "),
    new KeyDefinition(DIK_X           ,"X","xX  "),
    new KeyDefinition(DIK_C           ,"C","cC  "),
    new KeyDefinition(DIK_V           ,"V","vV  "),
    new KeyDefinition(DIK_B           ,"B","bB  "),
    new KeyDefinition(DIK_N           ,"N","nN  "),
    new KeyDefinition(DIK_M           ,"M","mM  "),
    new KeyDefinition(DIK_COMMA       ,"COMMA",",<  "),
    new KeyDefinition(DIK_PERIOD      ,"PERIOD",".>  "),
    new KeyDefinition(DIK_SLASH       ,"MENO","-_  "),
    new KeyDefinition(DIK_RSHIFT      ,"RSHIFT"),
    new KeyDefinition(DIK_MULTIPLY    ,"PAD_MULTIPLY","**  "),
    new KeyDefinition(DIK_LMENU       ,"LALT"),
    new KeyDefinition(DIK_SPACE       ,"SPACE","    "),
    new KeyDefinition(DIK_CAPITAL     ,"CAPSLOCK"),
    new KeyDefinition(DIK_F1          ,"F1"),
    new KeyDefinition(DIK_F2          ,"F2"),
    new KeyDefinition(DIK_F3          ,"F3"),
    new KeyDefinition(DIK_F4          ,"F4"),
    new KeyDefinition(DIK_F5          ,"F5"),
    new KeyDefinition(DIK_F6          ,"F6"),
    new KeyDefinition(DIK_F7          ,"F7"),
    new KeyDefinition(DIK_F8          ,"F8"),
    new KeyDefinition(DIK_F9          ,"F9"),
    new KeyDefinition(DIK_F10         ,"F10"),
    new KeyDefinition(DIK_NUMLOCK     ,"NUMLOCK"),
    new KeyDefinition(DIK_SCROLL      ,"SCROLLLOCK"),
    new KeyDefinition(DIK_NUMPAD7     ,"PAD_7","77  "),
    new KeyDefinition(DIK_NUMPAD8     ,"PAD_8","88  "),
    new KeyDefinition(DIK_NUMPAD9     ,"PAD_9","99  "),
    new KeyDefinition(DIK_SUBTRACT    ,"PAD_MINUS","--  "),
    new KeyDefinition(DIK_NUMPAD4     ,"PAD_4","44  "),
    new KeyDefinition(DIK_NUMPAD5     ,"PAD_5","55  "),
    new KeyDefinition(DIK_NUMPAD6     ,"PAD_6","66  "),
    new KeyDefinition(DIK_ADD         ,"PAD_PLUS","++  "),
    new KeyDefinition(DIK_NUMPAD1     ,"PAD_1","11  "),
    new KeyDefinition(DIK_NUMPAD2     ,"PAD_2","22  "),
    new KeyDefinition(DIK_NUMPAD3     ,"PAD_3","33  "),
    new KeyDefinition(DIK_NUMPAD0     ,"PAD_0","00  "),
    new KeyDefinition(DIK_DECIMAL     ,"PAD_DEL","..  "),
    //new KeyDefinition(DIK_OEM_102     ,"MAGGIORE","><  "),
    new KeyDefinition(DIK_F11         ,"F11"),
    new KeyDefinition(DIK_F12         ,"F12"),
    new KeyDefinition(DIK_PAUSE       ,"BREAK"),
    //new KeyDefinition(DIK_F13         ,"F13"),
    //new KeyDefinition(DIK_F14         ,"F14"),
    //new KeyDefinition(DIK_F15         ,"F15"),
    //new KeyDefinition(DIK_KANA        ,"KANA"),
    //new KeyDefinition(DIK_CONVERT     ,"CONVERT"),
    //new KeyDefinition(DIK_NOCONVERT   ,"NOCONVERT"),
    //new KeyDefinition(DIK_YEN         ,"YEN"),
    new KeyDefinition(DIK_NUMPADEQUALS,"PAD_EQUALS","==  "),
    //new KeyDefinition(DIK_CIRCUMFLEX  ,"CIRCUMFLEX"),
    new KeyDefinition(DIK_AT          ,"AT"),
    new KeyDefinition(DIK_COLON       ,"COLON"),
    new KeyDefinition(DIK_UNDERLINE   ,"UNDERLINE"),
    //new KeyDefinition(DIK_KANJI       ,"KANJI"),
    //new KeyDefinition(DIK_STOP        ,"STOP"),
    //new KeyDefinition(DIK_AX          ,"AX"),
    //new KeyDefinition(DIK_UNLABELED   ,"UNLABELED"),
    new KeyDefinition(DIK_NUMPADENTER ,"PAD_ENTER"),
    new KeyDefinition(DIK_RCONTROL    ,"RCTRL"),
    //new KeyDefinition(DIK_NUMPADCOMMA ,"PAD_COMMA",",,  "),
    new KeyDefinition(DIK_DIVIDE      ,"PAD_SLASH","//  "),
    new KeyDefinition(DIK_SYSRQ       ,"PRINT_SCREEN"),
    new KeyDefinition(DIK_RMENU       ,"RALT"),
    new KeyDefinition(DIK_HOME        ,"HOME"),
    new KeyDefinition(DIK_UP          ,"UP"),
    new KeyDefinition(DIK_PRIOR       ,"PGUP"),
    new KeyDefinition(DIK_LEFT        ,"LEFT"),
    new KeyDefinition(DIK_RIGHT       ,"RIGHT"),
    new KeyDefinition(DIK_END         ,"END"),
    new KeyDefinition(DIK_DOWN        ,"DOWN"),
    new KeyDefinition(DIK_NEXT        ,"PGDN"),
    new KeyDefinition(DIK_INSERT      ,"INS"),
    new KeyDefinition(DIK_DELETE      ,"DEL"),
    new KeyDefinition(DIK_LWIN        ,"LWIN"),
    new KeyDefinition(DIK_RWIN        ,"RWIN"),
    //new KeyDefinition(DIK_APPS        ,"APPS"),


    // mouse
    new KeyDefinition(DIK_MOUSE1      ,"MOUSE1"),
    new KeyDefinition(DIK_MOUSE2      ,"MOUSE2"),
    new KeyDefinition(DIK_MOUSE3      ,"MOUSE3"),
    new KeyDefinition(DIK_MOUSE4      ,"MOUSE4"),
    new KeyDefinition(DIK_MOUSE_WUP   ,"MWHEEL_UP"),
    new KeyDefinition(DIK_MOUSE_WDOWN ,"MWHEEL_DOWN"),
    // JOYSTICK
    new KeyDefinition(DIK_JOYBUTTON1  ,"J_BUTTON1"),
    new KeyDefinition(DIK_JOYBUTTON2  ,"J_BUTTON2"),
    new KeyDefinition(DIK_JOYBUTTON3  ,"J_BUTTON3"),
    new KeyDefinition(DIK_JOYBUTTON4  ,"J_BUTTON4"),
    new KeyDefinition(DIK_JOYBUTTON5  ,"J_BUTTON5"),
    new KeyDefinition(DIK_JOYBUTTON6  ,"J_BUTTON6"),
    new KeyDefinition(DIK_JOYBUTTON7  ,"J_BUTTON7"),
    new KeyDefinition(DIK_JOYBUTTON8  ,"J_BUTTON8"),
    new KeyDefinition(DIK_JOYBUTTON9  ,"J_BUTTON9"),
    new KeyDefinition(DIK_JOYBUTTON10 ,"J_BUTTON10"),
    new KeyDefinition(DIK_JOYBUTTON11 ,"J_BUTTON11"),
    new KeyDefinition(DIK_JOYBUTTON12 ,"J_BUTTON12"),
    new KeyDefinition(DIK_JOYBUTTON13 ,"J_BUTTON13"),
    new KeyDefinition(DIK_JOYBUTTON14 ,"J_BUTTON14"),
    new KeyDefinition(DIK_JOYBUTTON15 ,"J_BUTTON15"),
    new KeyDefinition(DIK_JOYBUTTON16 ,"J_BUTTON16"),
    new KeyDefinition(DIK_JOYBUTTON17 ,"J_BUTTON17"),
    new KeyDefinition(DIK_JOYBUTTON18 ,"J_BUTTON18"),
    new KeyDefinition(DIK_JOYBUTTON19 ,"J_BUTTON19"),
    //new KeyDefinition(DIK_JOYBUTTON20 ,"J_BUTTON20"),
    //new KeyDefinition(DIK_JOYBUTTON21 ,"J_BUTTON21"),
    //new KeyDefinition(DIK_JOYBUTTON22 ,"J_BUTTON22"),
    //new KeyDefinition(DIK_JOYBUTTON23 ,"J_BUTTON23"),
    //new KeyDefinition(DIK_JOYBUTTON24 ,"J_BUTTON24"),
    //new KeyDefinition(DIK_JOYBUTTON25 ,"J_BUTTON25"),
    //new KeyDefinition(DIK_JOYBUTTON26 ,"J_BUTTON26"),
    //new KeyDefinition(DIK_JOYBUTTON27 ,"J_BUTTON27"),
    //new KeyDefinition(DIK_JOYBUTTON28 ,"J_BUTTON28"),
    //new KeyDefinition(DIK_JOYBUTTON29 ,"J_BUTTON29"),
    //new KeyDefinition(DIK_JOYBUTTON30 ,"J_BUTTON30"),
    //new KeyDefinition(DIK_JOYBUTTON31 ,"J_BUTTON31"),
    //new KeyDefinition(DIK_JOYBUTTON32 ,"J_BUTTON32"),
    //new KeyDefinition(DIK_JOYHAT0     ,"J_HAT0"),
    //new KeyDefinition(DIK_JOYHAT45    ,"J_HAT45"),
    //new KeyDefinition(DIK_JOYHAT90    ,"J_HAT90"),
    //new KeyDefinition(DIK_JOYHAT135   ,"J_HAT135"),
    //new KeyDefinition(DIK_JOYHAT180   ,"J_HAT180"),
    //new KeyDefinition(DIK_JOYHAT225   ,"J_HAT225"),
    //new KeyDefinition(DIK_JOYHAT270   ,"J_HAT270"),
    //new KeyDefinition(DIK_JOYHAT315   ,"J_HAT315"),
};
};

public enum MMOD
{
    MMOD_NONE = 0,
    MMOD_SHIFT = 1,
    MMOD_CTRL = 2,
    MMOD_ALT = 3,
    MMOD_LAST
};
